parameters:
  versionSpec: '10.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: ${{ parameters.versionSpec }}
  displayName: 'Install Node.js'
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
      npm
    path: $(npm_config_cache)
  displayName: 'Cache npm'
- script: |
    npm install -g @angular/cli
    npm ci
  displayName: 'Install dependencies'
